---
netplan:
  interfaces:
    - name: eth1
      ipv4:
        - 192.168.3.5
        - 176.23.4.23
      dhcp4: "false"
      routes:
        - to: 10.10.10.0
          via: 10.10.10.4
        - to: 10.16.10.0
          via: 10.16.10.4
    - name: eth2
      ipv4:
        - 202.168.3.5
        - 10.23.4.23
        - 34.5.6.7
      dhcp4: "true"
      routes:
        - to: 192.10.10.0
          via: 192.10.10.4
        - to: 23.16.10.0
          via: 23.16.10.4