--- 
- name: Create nginx conf file for domain {{ item.domain }}
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ item.domain }}
  notify: reload_nginx

- name: Create softs link for  /etc/ngunx/sites-available/{{ item.domain }} file 
  file: 
    src: /etc/nginx/sites-available/{{ item.domain }}
    dest: /etc/nginx/sites-enabled/{{ item.domain }}
    state: link
  notify: reload_nginx 