---
- name: First Playbook
  hosts: devops-ansible
  gather_facts: false
  vars_files:
    - ./vars.yml
  tasks:
    - name: Ping
      ping:

    - name: Public IP
      debug: 
        var: ansible_facts

    - name: File yaratish
      file:
        path: /home/maruf/{{ fayl.path  }}
        state: "{{ fayl.state  }}"
        mode: "{{ fayl.mode  }}"
      with_items:
        - path: test1
          state: touch
          mode: 640
        - path: test2
          state: touch
          mode: 404
      loop_control:
        loop_var: fayl
     
    - name: Papka yaratish
      file:
        path: /home/maruf/{{ item  }}
        state: directory
      with_items:
        - test_folder1
        - test_folder2
        - test_folder3


