---
- name: First Playbook
  hosts: devops-ansible
  gather_facts: true
  vars_files:
    - ./vars.yml
  tasks:
    - name: Ping
      ping:
    - name: List Network Interfaces
      shell: "ip addr show | grep '^[0-9]' | awk '{print $2}' | sed 's/://'"
      register: interface_result
    - name: Get IP Addresses
      shell: "ip addr show {{ item }} | grep 'inet ' | awk '{print $2}'"
      register: ip_result
      loop: "{{ interface_result.stdout_lines }}"
    - name: Display Interface List
      debug:
        msg: item.stdout
      with_items: "{{ip_result.results}}"
    - name: Display IP Address
      debug:
        var: ansible_default_ipv4.address   
 

    # - name: Node ning OT ni ko'rsat
    #   debug: 
    #     var: ansible_facts.distribution

        # - name: File yaratish
    #   file:
    #     path: /Users/zafarsaidov/devops/ansible/{{ papka.path }}
    #     state: "{{ papka.state }}"
    #     mode: "{{ papka.mode }}"
    #   when: 
    #     - ansible_facts.distribution == "MacOSX" 
    #     - ansible_facts.architecture == "arm64"
    #   with_items:
    #     - path: test1
    #       state: directory
    #       mode: 755
    #     - path: test2
    #       state: touch
    #       mode: 600
    #     - path: test3
    #       state: touch
    #       mode: 404
    #   loop_control:
    #     loop_var: papka

    # - name: Papka yaratish
    #   file:
    #     path: /Users/zafarsaidov/devops/ansible/{{ item }}
    #     state: absent
    #   when: ansible_facts.distribution == "Ubuntu" or ansible_facts.architecture == "arm64"
    #   with_items:
    #     - test11
    #     - test21
    #     - test31
