---
- name: First Playbook
  hosts: devops-ansible
  gather_facts: true
  vars_files:
    - ./vars.yml
  tasks:
    - name: Ping
      ping:

    - name: Ip address
      debug:
        var: ansible_facts.all_ipv4_addresses

    - name: Bios Vendor
      debug:
        var: ansible_facts.bios_vendor
         
    - name: Architecture
      debug: 
        var: ansible_facts.architecture

    - name: Node ning OT ni ko'rsat
      debug: 
        var: ansible_facts.distribution

    # - name: File yaratish
    #   file:
    #     path: /Users/zafarsaidov/devops/ansible/{{ papka.path }}
    #     state: "{{ papka.state }}"
    #     mode: "{{ papka.mode }}"
    #   when: 
    #     - ansible_facts.distribution == "MacOSX" 
    #     - ansible_facts.architecture == "arm64"
    #   with_items:
    #     - path: test1
    #       state: directory
    #       mode: 755
    #     - path: test2
    #       state: touch
    #       mode: 600
    #     - path: test3
    #       state: touch
    #       mode: 404
    #   loop_control:
    #     loop_var: papka

    # - name: Papka yaratish
    #   file:
    #     path: /Users/zafarsaidov/devops/ansible/{{ item }}
    #     state: absent
    #   when: ansible_facts.distribution == "Ubuntu" or ansible_facts.architecture == "arm64"
    #   with_items:
    #     - test11
    #     - test21
    #     - test31
