---

netplan: 
  interfaces:
    - name: eth1
      ipv4:
        - 172.24.45.3
        - 192.168.20.10
      dhcp4: "false"
      routes:
        - to: 10.10.10.11
          via: 10.111.11.1
        - to: 10.14.12.3
          via: 10.14.12.25
    - name: eth2
      ipv4:
        - 101.24.45.3
        - 172.168.20.10
      dhcp4: "false"
      routes:
        - to: 101.10.10.11
          via: 102.111.11.1
        - to: 104.14.12.3
          via: 105.14.12.25
    - name: ens133333
      ipv4:
        - 101.24.45.3
        - 172.168.20.10
      dhcp4: "false"
      routes:
        - to: 101.10.10.11
          via: 102.111.11.1
        - to: 104.14.12.3
          via: 105.14.12.25
