---
- name: Initial Playbook
  hosts: devops-aws
  become: true
  gather_facts: false

   
  roles: 
    # - role: jamol/user_create
    # - role: jamol/ssh_keys
   
- name: server configuration
  hosts: devops-aws
  # become: true 
  gather_facts: true
  vars: 
    ansible_ssh_private_key_file: "{{ private_key_file }}"
    ansible_user: "{{ sudo_user }}"
    ansible_sudo_pass: "{{ sudo_pass }}"

  roles:
    # - role: jamol/sshd_conf

# - name: test 
#   hosts: devops-aws
#   gather_facts: true
#   vars: 
#     ansible_user: "{{ sudo_user }}"
#     ansible_port: "{{ sshd.port }}"
#     ansible_ssh_private_key_file: "{{ private_key_file }}"
    
#   tasks: 
#     - shell: whoami
#       register: result
#     - debug:
#         msg: "{{ result.stdout }}"

- name: Install commont tools
  hosts: devops-aws
  become: true
  gather_facts: true
  vars: 
    ansible_user: "{{ sudo_user }}"
    ansible_port: "{{ sshd.port }}"
    ansible_ssh_private_key_file: "{{ private_key_file }}"
  roles:
    # - role: jamol/common_tools
    # - role: jamol/kernel
    # - role: jamol/iptables 
    # - role: jamol/docker_install
    # - role: jamol/docker_run 
    # - role: jamol/certbot 
    # - role: jamol/nginx_install
    # - role: jamol/nginx_add_domen
    - role: jamol/check_domain