--- 
# tasks file for roles/jamol/docker_install
- name: Install docker packages
  remote_user: ubuntu
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
    - python3-pip
- name: Pip docker
  pip:
    name: 
      - docker 
      - docker-compose 
    state: present 
    executable: pip3
  tags:
    - docker
- name: add GPG key
  apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present 
  tags:
    - docker
- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker
- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
- name: Update apt cache
  apt: 
    update_cache: yes 

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
- name: "Add remote {{sudo_user}} user to docker group"
  user: 
    name: "{{ sudo_user }}"
    groups: "docker"
    append: yes


- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64 
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'