---
# tasks file for roles/jamol/docker_run
- name: Start flask projecct
  community.docker.docker_compose:
    project_name: "{{ item.name }}"
    definition: 
      version: "3"
      services: 
        app: 
          image: "{{ item.image }}"
          ports: "{{ item.ports }}"
  with_items: "{{ apps }}"