---
# tasks file for roles/jamol/script
- name: Run a script with arguments (free form)
  become: true
  script: "{{ username.path }}"
  register: result
- name: list contents
  debug:
    msg: "{{ item }}"
  loop: "{{ result.stdout_lines }}"
- name: std out
  debug: 
    msg: "{{ result.stdout }}"
- name: std error
  debug: 
    msg: "{{ result.stderr }}"

- name: List directory contents
  shell: ls /home/{{ ansible_user }}/directory
  register: dir_contents
- name: Check if directory is empty
  debug:
    msg: "Directory is empty."
  when: dir_contents.stdout == ""

    

# - name: Run a script with arguments (using 'cmd' parameter)
#   script:
#     executable: bash
#     cmd: "{{ username.path }}"
#     register: console
# - debug: msg="{{ console.stdout }}"
# - debug: msg="{{ console.stderror }}"


# - name: Change the working directory to somedir/ before executing the command.
#   shell: /tmp/script.sh
  
  
# - debug:
#     msg: " {{ stdout_line }}"


  
    