---
- name: First Playbook
  hosts: devops-ansible
  become: true
  gather_facts: true
  # vars_files:
  #   - ./vars.yml
  roles:
    # - role: zafar/set-timezone
    # - role: zafar/copy-file
  tasks:
    - name: Block of tasks
      become: true
      when: true
      block:
        # - name: Facts
        #   debug:
        #     var: ansible_facts
        - name: Command Whoami
          shell: whoami
          register: remote_user
        - name: User debug
          debug:
            var: remote_user
        - name: Module Command
          command: echo $HOME
        - name: Services
          shell: systemctl list-units | grep "active running" | grep cron
          register: services
          ignore_errors: true
        - name: Debug
          debug:
            var: services
        - name: Restarting test 
          debug:
            msg: "Ishlamadi"
          when: not services.stdout_lines
          changed_when: true
          notify: restart_cron
        - name: Stopping test
          debug:
            msg: "Ishladi"
          when: services.stdout_lines
          changed_when: true
          notify: stop_cron
  handlers:
    - name: restart_cron
      systemd:
        name: cron
        state: started
    - name: stop_cron
      systemd:
        name: cron
        state: stopped
# - name: Second Playbook
#   hosts: all-servers
#   gather_facts: true
#   # vars_files:
#   #   - ./vars.yml
#   roles:
#     # - role: zafar/set-timezone
#     # - role: zafar/copy-file
#   tasks:
#     # - name: Facts
#     #   debug:
#     #     var: ansible_facts
#     - name: Command Whoami
#       become_user: abdurauf
#       shell: whoami